### ISSUE TITLE
Rolling effect during capturing images

### ISSUE THREAD

**Issue by allsey87** [yorkrobotlab/pi-puck-ft903#1]
When I try to capture images from the Pi-Puck camera using the FT903 interface, I am getting the following [rolling-like effect in the captured images](https://github.com/yorkrobotlab/pi-puck-ft903/files/5353766/frames.zip).

Based on appearance of the robot and since the image comes out rotated by 90 degrees, I would say this is the PO3030. The EPuck revision is HWRev 1.1 (model number 1426). I am interfacing with it via the Pi-Puck board and standard UVC driver in Linux.

Kernel messages:
> [4.548141] usb 1-1.1: New USB device found, idVendor=0403, idProduct=0fd8, bcdDevice= 1.01
> [4.556788] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [4.564301] usb 1-1.1: Product: Pi-puck Camera Interface
> [4.569757] usb 1-1.1: Manufacturer: University of York
> [4.575107] usb 1-1.1: SerialNumber: 00010001
> ...
> [28.348629] uvcvideo: Found UVC 1.10 device Pi-puck Camera Interface (0403:0fd8)
> [28.356553] uvcvideo: Failed to set UVC probe control : -32 (exp. 34).
> [28.430036] uvcvideo 1-1.1:1.0: Entity type for entity Processing 5 was not initialized!
> [28.466636] uvcvideo 1-1.1:1.0: Entity type for entity Camera 1 was not initialized!
> [28.498124] input: Pi-puck Camera Interface: Pi-pu as /devices/platform/soc/20980000.usb/usb1/1-1/1-1.1/1-1.1:1.0/input/input2

Formats reported with `yavta --enum-formats /dev/video0`
> Device /dev/video0 opened.
> Device Pi-puck Camera Interface: Pi-pu on usb-20980000.usb-1.1 is a video output (without mplanes) device.
> - Available formats:
> Format 0: YUYV (56595559)
> Type: Video capture (1)
> Name: YUYV 4:2:2
> Frame size: 640x480 (1/15)
> 
> Video format: YUYV (56595559) 640x480 (stride 1280) field none buffer size 614400

Frames captured using `yavta -f YUYV -s 640x480 -n1 -c10 -F /dev/video0`
> Device /dev/video0 opened.
> Device Pi-puck Camera Interface: Pi-pu on usb-20980000.usb-1.1 is a video output (without mplanes) device.
> Video format set: YUYV (56595559) 640x480 (stride 1280) field none buffer size 614400
> Video format: YUYV (56595559) 640x480 (stride 1280) field none buffer size 614400
> 1 buffers requested.
> length: 614400 offset: 0 timestamp type/source: mono/SoE
> Buffer 0/0 mapped at address 0xb6d01000.
> 0 (0) [-] none 0 614400 B 221.241023 221.299764 17.902 fps ts mono/SoE
> 1 (0) [-] none 2 614400 B 221.358184 221.417045 8.535 fps ts mono/SoE
> 2 (0) [-] none 4 614400 B 221.475378 221.534159 8.533 fps ts mono/SoE
> 3 (0) [-] none 6 614400 B 221.592559 221.651427 8.534 fps ts mono/SoE
> 4 (0) [-] none 8 614400 B 221.709763 221.768620 8.532 fps ts mono/SoE
> 5 (0) [-] none 10 614400 B 221.826938 221.885710 8.534 fps ts mono/SoE
> 6 (0) [-] none 12 614400 B 221.944137 222.002997 8.532 fps ts mono/SoE
> 7 (0) [-] none 14 614400 B 222.061316 222.120332 8.534 fps ts mono/SoE
> 8 (0) [-] none 16 614400 B 222.178515 222.237275 8.532 fps ts mono/SoE
> 9 (0) [-] none 18 614400 B 222.295694 222.354459 8.534 fps ts mono/SoE
> Captured 10 frames in 1.169295 seconds (8.552162 fps, 5254448.193142 B/s).
> 1 buffers released.

Conversion from raw images to PNGs done with Imagemagick, i.e., `convert -size 640x480 -depth 8 UYVY:frame-XYZ.bin frame-XYZ.png`

**Comment by RussellJoyce** [comment]
Don't think I've seen that exact issue before, although looks like some kind of vsync problem. I thought we'd fixed all of these, but maybe not...

I'll try the same commands you ran on my PO6030 and PO8030 e-pucks this afternoon and see if they work ok on them (I've not used `yavta` before). If they work fine then @alanmillard can try on one of his HWRev 1.1s (I only have HWRev 1.2s and an e-puck2 here).

**Comment by allsey87** [comment]
@RussellJoyce great, let me know if you need any more information from my end

**Comment by RussellJoyce** [comment]
From @alanmillard's playing with the PO3030, it looks like you're not setting up the camera sensor before reading images, which can be done by running [this script](https://github.com/yorkrobotlab/pi-puck/blob/master/utilities/e-puck-camera-init) on the Raspberry Pi.

Unfortunately we can't set up the camera sensor from the FT903 directly because the Raspberry Pi is the I2C master, so we have to use this slightly hacky workaround. In our Raspbian distribution we use a service to do this on every boot (see [here](https://github.com/yorkrobotlab/pi-puck-packages/blob/master/pi-puck-utils/e-puck-camera-init.service)), but otherwise it'll need to be run manually after each time the e-puck is powered on.

The default behaviour for each of the three possible sensors is a bit different (and also doesn't seem to necessarily match their datasheets), so this script mostly just tries to get them into the same consistent state, and to match the format, resolution and frame rate to what we hard-coded into the FT903 UVC driver (16 bits-per-pixel YUYV/YCbYCr, 640x480, 15fps).

One issue with this change is that your ImageMagick command will no longer convert the image properly, as it expects UYVY data ordering instead of YUYV, and ImageMagick doesn't seem to have a mode that works with YUYV directly. This means the images you get will now be in sync, but ImageMagick will break their colours.
Given this, there are three options I've thought of to get the images how you want them:

1. Swap the byte ordering manually before passing the image data to ImageMagick, using something like the following:

```
#!/usr/bin/env python3

import sys

with open(sys.argv[1], "rb") as in_file, open(sys.argv[2], "wb") as out_file:
    for i in range(0, 640*480):
        pixel = in_file.read(2)
        out_file.write(pixel[::-1])
```

2. Ditch ImageMagick and use a capture program that interprets the data format according to the UVC headers and converts the image to a viewable format itself, for example [fswebcam](https://www.raspberrypi.org/documentation/usage/webcams/README.md). Another good application is [dmxwebcam](https://github.com/yorkrobotlab/dmxwebcam), which outputs a nice smooth video stream from the camera over the Raspberry Pi's HDMI port, and is very useful for testing.

3. Change the sensor setup script (and the FT903 driver if you want V4L2 programs to recognise the new format natively) to make the sensor output UYVY/CbYCrY instead (I think this can be done by setting register `0x4E` to `0x00` on the PO3030). This is probably overkill though, unless you have a specific reason for the data to be in this format in an actual application.

Our sensor setup script is certainly not the only way things can work though (and is currently a bit of a hacked-together mess). For example, the image colour/contrast/brightness/etc. from the sensor could probably be improved somewhat by tuning register values for a specific robot/environment. An ideal solution would probably allow sensor values to be tuned at runtime, and then saved so they can be recalled on the next boot. I've been meaning to play around with this for a long time, but have never got round to it... It might also be possible to provide dynamic switching of resolutions, colour spaces and frame rates in the UVC driver with some kind of communication with the FT903, so it works more like a normal webcam rather than having just one fixed output type.

Anyway, that got a bit off topic, but hopefully running that script fixes the sync issue, and if not let us know!

**Comment by allsey87** [comment]
Thanks for the info, @RussellJoyce, I'll probably add the contents of that script to a simple kernel module that loads on boot

**Comment by allsey87** [comment]
The routines in the script worked nicely! I converted the file using `ffmpeg` i.e., with: `ffmpeg -f rawvideo -s 640x480 -pix_fmt yuyv422 -i input.raw output.png`. 
![frame-000001](https://user-images.githubusercontent.com/3796345/96254390-816f8a00-0fb5-11eb-9cda-dc86ccc4168d.png)
I converted the python script into a kernel module and uploaded it [here](https://github.com/yorkrobotlab/pi-puck-ft903/files/5391230/epuck-cameraconf.zip) should it be of any use to you :) Thanks again for your help!
